name: Docker Build Workflow

on:
  workflow_call:
    inputs:
      environment:
        description: 'Set environment'
        required: true
        type: string
      run-environment: 
        description: 'Build environment'
        required: true
        type: string
      runs-on:
        required: false
        type: string
        default: ubuntu-latest
      region:
        required: false
        type: string
        default: sa-east-1
      aws-account:
        required: true
        type: string
      role:
        required: true
        type: string
    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
      vault_token:
        required: true
      maven_aws_access_key:
        required: true
      maven_aws_secret_access_key:
        required: true
      github_user:
        required: true
      github_personal_token:
        required: true
    outputs:
      image-tag:
        description: "Docker tag image"
        value: ${{ jobs.build-image.outputs.image-tag }}

jobs:
  build-image:
    environment: ${{ inputs.environment }}
    name: Build
    runs-on: ${{ inputs.runs-on }}
    outputs:
      image-tag: ${{ steps.image-tag.outputs.image-tag }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.aws-access-key-id }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.aws-secret-access-key }}
      VAULT_TOKEN: ${{ secrets.vault_token }}
      MAVEN_AWS_ACCESS_KEY: ${{ secrets.maven_aws_access_key }}
      MAVEN_AWS_SECRET_ACCESS_KEY: ${{ secrets.maven_aws_secret_access_key }}
      GITHUB_USER: ${{ secrets.github_user }}
      GITHUB_PERSONAL_TOKEN: ${{ secrets.github_personal_token }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Tag  
        run: |
          echo "image_tag=${{ inputs.environment }}-$(git log | head -n 1 | cut -c8-15)" >> $GITHUB_ENV
          source $GITHUB_ENV
          echo "Image Tag: $image_tag"
          echo "::set-output name=image-tag::$image_tag"
        id: image-tag
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.region }}
          role-to-assume: arn:aws:iam::${{ inputs.aws-account }}:role/${{ inputs.role }}
          role-duration-seconds: 1200

      - name: ECR Login
        run: |
          aws ecr get-login-password --region ${{ inputs.region }} | docker login --username AWS --password-stdin ${{ inputs.aws-account }}.dkr.ecr.${{ inputs.region }}.amazonaws.com
      
      - name: Build Image
        run: |
          docker image build -t ${{ inputs.aws-account }}.dkr.ecr.${{ inputs.region }}.amazonaws.com/${{ github.repository }}:${{ env.image_tag }} --build-arg GITHUB_TOKEN=${{ secrets.GH_PAT }} --build-arg RUN_ENVIRONMENT=${{ inputs.run-environment }} --build-arg VAULT_TOKEN=${{ env.VAULT_TOKEN }} --build-arg AWS_ACCOUNT=${{ inputs.aws-account }} --build-arg REGION=${{ inputs.region }} --build-arg AWS_ACCESS_KEY=${{ env.MAVEN_AWS_ACCESS_KEY }} --build-arg AWS_SECRET_ACCESS_KEY=${{ env.MAVEN_AWS_SECRET_ACCESS_KEY }} --build-arg GITHUB_USER=${{ env.GITHUB_USER }} --build-arg GITHUB_PERSONAL_TOKEN=${{ env.GITHUB_PERSONAL_TOKEN }} .
          docker image tag ${{ inputs.aws-account }}.dkr.ecr.${{ inputs.region }}.amazonaws.com/${{ github.repository }}:${{ env.image_tag }} ${{ inputs.aws-account }}.dkr.ecr.${{ inputs.region }}.amazonaws.com/${{ github.repository }}:latest
      
      - name: Push to ECR
        run: |
          docker image push ${{ inputs.aws-account }}.dkr.ecr.${{ inputs.region }}.amazonaws.com/${{ github.repository }}:${{ env.image_tag }}
          docker image push ${{ inputs.aws-account }}.dkr.ecr.${{ inputs.region }}.amazonaws.com/${{ github.repository }}:latest
