name: Docker Build Workflow

on:
  workflow_call:
    inputs:
      environment:
        description: 'Set environment'
        required: true
        type: string
      run-environment: 
        description: 'Build environment'
        required: true
        type: string
      runs-on:
        required: false
        type: string
        default: ubuntu-latest
      region:
        required: false
        type: string
        default: sa-east-1
      aws-account:
        required: true
        type: string
      role:
        required: true
        type: string
    outputs:
      image-tag:
        description: "Docker tag image"
        value: ${{ jobs.build-image.outputs.image-tag }}

jobs:
  build-image:
    environment: ${{ inputs.environment }}
    name: Build
    runs-on: ${{ inputs.runs-on }}
    outputs:
      image-tag: ${{ steps.image-tag.outputs.image-tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Tag  
        run: |
          echo "image_tag=${{ inputs.environment }}-$(git log | head -n 1 | cut -c8-15)" >> $GITHUB_ENV
          source $GITHUB_ENV
          echo "Image Tag: $image_tag"
          echo "::set-output name=image-tag::$image_tag"
        id: image-tag
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.region }}
          role-to-assume: arn:aws:iam::${{ inputs.aws-account }}:role/${{ inputs.role }}
          role-duration-seconds: 1200
      
      - name: Build Image
        run: |
          docker image build -t ${{ inputs.aws-account }}.dkr.ecr.${{ inputs.region }}.amazonaws.com/${{ github.repository }}:${{ env.image_tag }} --build-arg GITHUB_TOKEN=${{ secrets.GH_PAT }} --build-arg RUN_ENVIRONMENT=${{ inputs.run-environment }} --build-arg VAULT_TOKEN=${{ secrets.VAULT_TOKEN }} --build-arg AWS_ACCOUNT=${{ inputs.aws-account }} .
          docker image tag ${{ inputs.aws-account }}.dkr.ecr.${{ inputs.region }}.amazonaws.com/${{ github.repository }}:${{ env.image_tag }} ${{ inputs.aws-account }}.dkr.ecr.${{ inputs.region }}.amazonaws.com/${{ github.repository }}:latest
      
      - name: ECR Login
        run: |
          aws ecr get-login-password --region ${{ inputs.region }} | docker login --username AWS --password-stdin ${{ inputs.aws-account }}.dkr.ecr.${{ inputs.region }}.amazonaws.com

      - name: Push to ECR
        run: |
          docker image push ${{ inputs.aws-account }}.dkr.ecr.${{ inputs.region }}.amazonaws.com/${{ github.repository }}:${{ env.image_tag }}
          docker image push ${{ inputs.aws-account }}.dkr.ecr.${{ inputs.region }}.amazonaws.com/${{ github.repository }}:latest