name: Create Pull Request Workflow

on:
  workflow_call:
    inputs:
      origin-branch:
        description: 'Branch origem do PR. Caso campo esteja vazio sera utilizada a branch atual do workflow.'
        required: false
        type: string
      target-branch:
        description: 'Branch de destino do PR'
        required: true
        type: string
      custom-title:
        required: false
        type: string
        default: 'PR criado automaticamente.'
      custom-body:
        required: false
        type: string
      runs-on:
        required: false
        type: string
        default: ubuntu-latest
jobs:
  pull-request:
    name: Create
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Get Origin Branch Name
        run: |
          if [ -z "${{ inputs.origin-branch }}" ]; then
            echo "branch_name=${{ github.ref_name }}" >> $GITHUB_ENV
          else
            echo "branch_name=${{ inputs.origin-branch }}" >> $GITHUB_ENV
          fi
          source $GITHUB_ENV
          echo "Use $branch_name branch"
          
      - name: Check Pull Request
        run: |
          curl -o check_pull_head_branch \
          --url https://api.github.com/repos/${{ github.repository }}/pulls \
          --header "authorization: Bearer ${{ github.token }}" \
          --header "content-type: application/json"
          echo "pull_head_branch=$(cat check_pull_head_branch | jq -r '.[].head | select (.ref == "${{ github.ref_name }}")|.ref')" >> $GITHUB_ENV
      
      - name: Auto Pull Request
        run: |
          if [ -z "${{ env.pull_head_branch }}" ]; then
            curl --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/pulls \
            --header 'authorization: Bearer ${{ github.token }}' \
            --header 'content-type: application/json' \
            --data '{
              "title": "${{ inputs.custom-title }} ${{ inputs.target-branch }} < ${{ env.branch_name }}",
              "body": "${{ inputs.custom-body }}",
              "head": "${{ env.branch_name }}",
              "base": "${{ inputs.target-branch }}"
              }' \
            --fail
            echo 'Pull request criado!!!'
          else 
            echo 'Já existe um Pull Request criado da branch ${{ env.branch_name }} para branch ${{ inputs.target-branch }}'
          fi