name: SonarQube Code Scan

on:
  workflow_call:
    inputs:
      environment:
        description: 'Set environment'
        required: true
        type: string
      runs-on:
        required: false
        type: string
        default: ubuntu-latest
    secrets:
      sonar-token:
        required: true
      sonar-host-url:
        required: true

jobs:
  sonarqube:
    name: Scan
    runs-on: ${{ inputs.runs-on }}
    env:
      SONAR_TOKEN: ${{ secrets.sonar-token }}
      SONAR_HOST_URL: ${{ secrets.sonar-host-url }}
    steps:
    - name: Checkout 
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set Tag  
      run: |
        echo "image_tag=${{ inputs.environment }}-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        source $GITHUB_ENV
        echo "Image Tag: $image_tag"
        echo "image-tag=$image_tag" >> $GITHUB_OUTPUT
      id: image-tag
   
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ env.SONAR_HOST_URL }}
      with:
        args: >
          -Dsonar.projectVersion=${{ env.image_tag }}